parameters {
    // Common Param inputs used across all deployments
    string(name: 'stackName', defaultValue: 'upc', description: 'The Stack to which code will be deployed.')
 string(name: 'stackNameToDelete', defaultValue: 'upc1', description: 'The Stack which needs to be deleted.')
    string(name: "env", defaultValue: 'dev', description: 'env name')
    string(name: 'region', defaultValue: 'us-west-2', description: 'AWS Region')
    string(name: 'awsAccountId', defaultValue: '943150447085', description: "int account:064790629266, dev account:943150447085, qa account:595570980330")
    choice(name: 'buildType', choices:['sprint', 'daily', 'manual'], description: "Specifies build type to use")
    string(name: 'buildLabel', defaultValue: '', description: ' Build Label to use')
    string(name: 'branchName', defaultValue: 'upc14-st2dev', description: ' Branch to use')
string(name: 'version', description: 'Version no. for the build ex. 1.4st1,1.4st2,1.4')
    string(name: 'msNamespace', defaultValue: 'microservices',description: 'Namespace where microservices are present')
    string(name: 'uPathNamespace', defaultValue: 'uPath Namespace',description: 'Namespace where upath is deployed')
    string(name: 'redisNamespace', defaultValue: 'redis',description: 'Namespace where redis is running')
    string(name: 'virtuosoBranchName', defaultValue: 'refs/heads/upc14-st2dev', description: 'Virtuoso branch name')
string(name: 'frontendBranchName', defaultValue: 'upc14-st2dev', description: ' Frontend branch name')
    string(name: 'upathKeyPairName', defaultValue: 'upc1-dev-jenkins', description: 'Virtuoso branch name')
    string(name: 'tenantAlias', defaultValue: 'dailyTestTenant', description: 'tenant alias')
    string(name: 'onboardTenantUUID', defaultValue: '')
    string(name: 'cloudwatchAlarmEmailIds', defaultValue: '')
    string(name: 'apiGatewayName', defaultValue: 'uPath-Cloud-rest-api')
    string(name: "authorizerURI", defaultValue:"arn:aws:lambda:us-west-2:468280580845:function:appdevus-product-authorizer",  description: 'Navify Authorizer URI lamba ARN')
string(name: "devaccountAmiId", defaultValue: 'ami-01286da360c441340', description: 'Windows Latest platform hardened AMI from Dev Account for Algorithms, IOT, ROI..etc')
  string(name: "algoBranchName", defaultValue: 'upc14-st2dev', description: 'RUO algorithm branch name')
  string(name: 'amiID', defaultValue: 'ami-0865e3a43448ee2c4', description: 'Linux EKS Latest platform hardened AMI from respective AWS Account for EKS-Cluster creation')
    string(name: 'SMTPSecretUsername', defaultValue: '', description: 'Enter the SMTP user for the secrete name "/upath-{Environment}/${StackName}/infra/smtp/username"')
password(name: 'SMTPSecretPassword', defaultValue: '', description: 'Enter the SMTP user for the secrete password "/upath-{Environment}/${StackName}/infra/smtp/password"')
    string(name: 'AWSAccountIDstoShareECRRepository', defaultValue: "'arn:aws:iam::064790629266:root','arn:aws:iam::595570980330:root','arn:aws:iam::765911385762:root','arn:aws:iam::995841348831:root','arn:aws:iam::489715691119:root'", description: 'Enter the list of AWS account IDs in the given format to share the ECR Repository(Exclude Current AWS Account ID)')

    // Switches to turn on/off deployments
    booleanParam(name: 'deleteStack', defaultValue: false, description: "Perform Stack Deletion")
    booleanParam(name: 'triggerBuildBeforeDeploy', defaultValue: true, description: "Trigger build of all microservices and Upath")
    booleanParam(name: 'deployCoreStack', defaultValue: true, description: "Deploy Core Stack")
    booleanParam(name: 'deploySchemaMigratorLambda', defaultValue: true, description: "Deploy Schema Migrator Lambda")
    booleanParam(name: 'deployTenantOnboardingLambda', defaultValue: true, description: "Deploy Tenant Onboarding Lambda")
    booleanParam(name: 'createVirtuosoSchema', defaultValue: true, description: "Create Vituoso Schema")
    booleanParam(name: 'createAlgoSchema', defaultValue: true, description: "Create Algorithm Schema")
    booleanParam(name: 'deployConfigService', defaultValue: true, description: "Deploy Config Service")
    booleanParam(name: 'deployI18nService', defaultValue: true, description: "Deploy i18n Service")
    booleanParam(name: 'deployTileService', defaultValue: true, description: "Deploy Tile/IOT Service")
    booleanParam(name: 'deployMetaDataService', defaultValue: true, description: "Deploy Image Metadata Service")
    booleanParam(name: 'deployROIService', defaultValue: true, description: "Deploy ROI Service")
    booleanParam(name: 'deployWSAService', defaultValue: true, description: "Deploy WSA Service")
    booleanParam(name: 'deployUploadService', defaultValue: true, description: "Deploy Image Upload Service")
    booleanParam(name: 'deployImageDeletionService', defaultValue: true, description: "Deploy Image Deletion Service")
    booleanParam(name: 'deploySearchService', defaultValue: true, description: "Deploy Search Service")
    booleanParam(name: 'deployJobManagementService', defaultValue: true, description: "Deploy Job Management Service")
booleanParam(name: 'deployConnectInService', defaultValue: true, description: "Deploy Connect In Service")
booleanParam(name: 'deployConnectOutService', defaultValue: true, description: "Deploy Connect Out Service")
booleanParam(name: 'deployRegistrationService', defaultValue: true, description: "Deploy Registration Service")
    booleanParam(name: 'deployAlgoHer2', defaultValue: true, description: "Deploy Her2 Algorithm Service")
    booleanParam(name: 'deployAlgoHer2Dualish', defaultValue: true, description: "Deploy Her2DualIsh Algorithm Service")
    booleanParam(name: 'deployAlgoHer2Dualish101', defaultValue: true, description: "Deploy Her2DualIsh 1.0.1 Algorithm Service")
    booleanParam(name: 'deployAlgoEr', defaultValue: true, description: "Deploy ER Algorithm Service")
    booleanParam(name: 'deployAlgoPr', defaultValue: true, description: "Deploy PR Algorithm Service")
    booleanParam(name: 'deployAlgoPdl', defaultValue: true, description: "Deploy PDL1 Algorithm Service")
    booleanParam(name: 'deployAlgoKI67', defaultValue: true, description: "Deploy KI67 Algorithm Service")
    booleanParam(name: 'deployAlgoIVDHer2Dualish', defaultValue: true, description: "Deploy IVD Her2DualIsh Algorithm Service")
    booleanParam(name: 'deployAlgoIVDHer2', defaultValue: true, description: "Deploy IVD Her2 Algorithm Service")
    booleanParam(name: 'deployAlgoIVDPdl', defaultValue: true, description: "Deploy IVD PDL1 Algorithm Service")
    booleanParam(name: 'deployUpathRestApp', defaultValue: true, description: "Deploy UPath Rest App Service")
    booleanParam(name: 'deployApiGateway', defaultValue: false, description: "Update API Gateway to VPC Link")

    booleanParam(name: 'executeOnboardTenant', defaultValue: true, description: "Onboard a Tenant ")
    booleanParam(name: 'executeDeleteTestTenant', defaultValue: true, description: "Delete a given Tenant")
booleanParam(name: 'deployFrontend', defaultValue: true, description: "Deploy Frontend")
    booleanParam(name: 'executeCloudwatchAlarms', defaultValue: true, description: "Create cloud watch Alarms ")
    booleanParam(name: 'parallelizeDeleteStackAndBuild', defaultValue: false, description: "Parallelly execute Stack deletion and Code Build")
}


parameters {
       string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

       text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

       booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

       choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

       password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
